resolver: lts-21.22
packages:
- 'genvalidity'
- 'genvalidity-aeson'
- 'genvalidity-bytestring'
- 'genvalidity-case-insensitive'
- 'genvalidity-containers'
- 'genvalidity-criterion'
- 'genvalidity-hspec'
- 'genvalidity-hspec-aeson'
- 'genvalidity-hspec-binary'
- 'genvalidity-hspec-cereal'
- 'genvalidity-hspec-hashable'
- 'genvalidity-hspec-optics'
- 'genvalidity-hspec-persistent'
- 'genvalidity-network-uri'
- 'genvalidity-path'
- 'genvalidity-persistent'
- 'genvalidity-property'
- 'genvalidity-scientific'
- 'genvalidity-sydtest'
- 'genvalidity-sydtest-aeson'
- 'genvalidity-sydtest-hashable'
- 'genvalidity-sydtest-lens'
- 'genvalidity-sydtest-persistent'
- 'genvalidity-text'
- 'genvalidity-time'
- 'genvalidity-unordered-containers'
- 'genvalidity-uuid'
- 'genvalidity-vector'
- 'validity'
- 'validity-aeson'
- 'validity-bytestring'
- 'validity-case-insensitive'
- 'validity-containers'
- 'validity-network-uri'
- 'validity-path'
- 'validity-persistent'
- 'validity-primitive'
- 'validity-scientific'
- 'validity-text'
- 'validity-time'
- 'validity-unordered-containers'
- 'validity-uuid'
- 'validity-vector'

extra-deps:
- github: NorfairKing/autodocodec
  commit: 5f23727689555789389ae4fbf41f674d43325814
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

- github: NorfairKing/safe-coloured-text
  commit: b4fd34585472a8b5aaec942bb1bd0748fa3d5aa0
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: dcd230e48f164594a473925fa0dbbaf956eb6848
  subdirs:
    - sydtest
    - sydtest-discover

ghc-options:
  "$locals": -Weverything -Wno-all-missed-specialisations -Wno-implicit-prelude -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module -Wno-safe -Wno-unsafe -Wno-missing-import-lists -Wno-missing-kind-signatures -Wno-missing-deriving-strategies -Wno-monomorphism-restriction -Wno-missing-export-lists -Wno-missing-local-signatures

system-ghc: true
nix:
  enable: false
with-hpack: hpack
