resolver: lts-14.22
packages:
- 'genvalidity'
- 'genvalidity-aeson'
- 'genvalidity-bytestring'
- 'genvalidity-containers'
- 'genvalidity-criterion'
- 'genvalidity-hspec'
- 'genvalidity-hspec-aeson'
- 'genvalidity-hspec-binary'
- 'genvalidity-hspec-cereal'
- 'genvalidity-hspec-hashable'
- 'genvalidity-hspec-optics'
- 'genvalidity-hspec-persistent'
- 'genvalidity-path'
- 'genvalidity-property'
- 'genvalidity-scientific'
- 'genvalidity-text'
- 'genvalidity-time'
- 'genvalidity-unordered-containers'
- 'genvalidity-uuid'
- 'genvalidity-vector'
- 'validity'
- 'validity-aeson'
- 'validity-bytestring'
- 'validity-containers'
- 'validity-path'
- 'validity-primitive'
- 'validity-scientific'
- 'validity-text'
- 'validity-time'
- 'validity-unordered-containers'
- 'validity-uuid'
- 'validity-vector'
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/3b5f3d1cb181cd91a5a1ce1d220fef6ffd998c6a.tar.gz" ]
  add-gc-roots: true
  pure: true
  packages:
  - zlib
