resolver: lts-22.22
packages:
- 'genvalidity'
- 'genvalidity-aeson'
- 'genvalidity-bytestring'
- 'genvalidity-case-insensitive'
- 'genvalidity-containers'
- 'genvalidity-criterion'
- 'genvalidity-dlist'
- 'genvalidity-hspec'
- 'genvalidity-hspec-aeson'
- 'genvalidity-hspec-binary'
- 'genvalidity-hspec-cereal'
- 'genvalidity-hspec-hashable'
- 'genvalidity-hspec-optics'
- 'genvalidity-hspec-persistent'
- 'genvalidity-network-uri'
- 'genvalidity-path'
- 'genvalidity-persistent'
- 'genvalidity-property'
- 'genvalidity-scientific'
- 'genvalidity-sydtest'
- 'genvalidity-sydtest-aeson'
- 'genvalidity-sydtest-hashable'
- 'genvalidity-sydtest-lens'
- 'genvalidity-sydtest-persistent'
- 'genvalidity-text'
- 'genvalidity-time'
- 'genvalidity-unordered-containers'
- 'genvalidity-uuid'
- 'genvalidity-vector'
- 'validity'
- 'validity-aeson'
- 'validity-bytestring'
- 'validity-case-insensitive'
- 'validity-containers'
- 'validity-dlist'
- 'validity-network-uri'
- 'validity-path'
- 'validity-persistent'
- 'validity-primitive'
- 'validity-scientific'
- 'validity-text'
- 'validity-time'
- 'validity-unordered-containers'
- 'validity-uuid'
- 'validity-vector'

extra-deps:
- github: NorfairKing/autodocodec
  commit: 5f23727689555789389ae4fbf41f674d43325814
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

- github: NorfairKing/safe-coloured-text
  commit: b4fd34585472a8b5aaec942bb1bd0748fa3d5aa0
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 074ace83d237dd602fbd006626a3958407a57fed
  subdirs:
    - sydtest
    - sydtest-discover

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack
