resolver: lts-23.19
packages:
- 'genvalidity'
- 'genvalidity-aeson'
- 'genvalidity-bytestring'
- 'genvalidity-case-insensitive'
- 'genvalidity-containers'
- 'genvalidity-criterion'
- 'genvalidity-dlist'
- 'genvalidity-hspec'
- 'genvalidity-hspec-aeson'
- 'genvalidity-hspec-binary'
- 'genvalidity-hspec-cereal'
- 'genvalidity-hspec-hashable'
- 'genvalidity-hspec-optics'
- 'genvalidity-hspec-persistent'
- 'genvalidity-network-uri'
- 'genvalidity-path'
- 'genvalidity-persistent'
- 'genvalidity-property'
- 'genvalidity-scientific'
- 'genvalidity-sydtest'
- 'genvalidity-sydtest-aeson'
- 'genvalidity-sydtest-hashable'
- 'genvalidity-sydtest-lens'
- 'genvalidity-sydtest-persistent'
- 'genvalidity-text'
- 'genvalidity-time'
- 'genvalidity-unordered-containers'
- 'genvalidity-uuid'
- 'genvalidity-vector'
- 'validity'
- 'validity-aeson'
- 'validity-bytestring'
- 'validity-case-insensitive'
- 'validity-containers'
- 'validity-dlist'
- 'validity-network-uri'
- 'validity-path'
- 'validity-persistent'
- 'validity-primitive'
- 'validity-scientific'
- 'validity-text'
- 'validity-time'
- 'validity-unordered-containers'
- 'validity-uuid'
- 'validity-vector'

extra-deps:
- github: NorfairKing/fast-myers-diff
  commit: d7c1a675af3889698b987485a630f96a993226fa
  subdirs:
    - fast-myers-diff
- github: NorfairKing/opt-env-conf
  commit: 44c868aea2703dddba3d43e23f79bcdb3297eb50
  subdirs:
    - opt-env-conf
    - opt-env-conf-test
- github: NorfairKing/autodocodec
  commit: be4aba9ef133520a8a4087aa26915aaabf1376a7
  subdirs:
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema
    - autodocodec-yaml

- github: NorfairKing/safe-coloured-text
  commit: 046f10147a058c00c2706d98c341219e3cbc7669
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: aab13681d89f0875411f2ac2b8d7dd7822869b5f
  subdirs:
    - sydtest
    - sydtest-discover

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack
