name: validity-unordered-containers
version: '0.2.0.3'
synopsis: Validity instances for unordered-containers
category: Validity
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2017-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

dependencies:
- base >=4.7 && <5
- validity >=0.5
- unordered-containers >=0.2.7
- hashable

library:
  source-dirs: src
