name: validity-text
version: '0.3.1.2'
synopsis: Validity instances for text
category: Web
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

dependencies:
- base >=4.7 && <5
- validity >=0.12
- text
- bytestring

library:
  source-dirs: src
