name: genvalidity-hspec-binary
version: '1.0.0.0'
synopsis: Standard spec's for binary-related Instances
description: Standard spec's for cereal-related Instances, see https://hackage.haskell.org/package/binary.
category: Testing
author: Nick Van den Broeck
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >=4.9 && <=5
- hspec
- binary

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - deepseq
  - genvalidity >= 1.0
  - genvalidity-hspec >=0.6

tests:
  genvalidity-hspec-binary-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - validity >=0.9
    - genvalidity
    - genvalidity-property
    - genvalidity-hspec-binary
