name: genvalidity-hspec
version: '0.5.0.0'
synopsis: Standard spec's for GenValidity instances
description: ! 'Note: There are companion packages for this library:


  * <https://hackage.haskell.org/package/genvalidity-hspec-aeson genvalidity-hspec-aeson>


  * <https://hackage.haskell.org/package/genvalidity-hspec-binary genvalidity-hspec-binary>


  * <https://hackage.haskell.org/package/genvalidity-hspec-cereal genvalidity-hspec-cereal>


  * <https://hackage.haskell.org/package/genvalidity-hspec-hashable genvalidity-hspec-hashable>'
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- QuickCheck
- hspec-core
library:
  source-dirs: src
  exposed-modules:
  - Test.Validity
  - Test.Validity.Applicative
  - Test.Validity.Arbitrary
  - Test.Validity.Eq
  - Test.Validity.Functor
  - Test.Validity.GenRelativeValidity
  - Test.Validity.GenValidity
  - Test.Validity.Monad
  - Test.Validity.Monoid
  - Test.Validity.Ord
  - Test.Validity.RelativeValidity
  - Test.Validity.Shrinking
  - Test.Validity.Utils
  dependencies:
  - base >=4.9 && <5
  - genvalidity >=0.4 && <0.5
  - genvalidity-property >=0.1 && <0.2
  - hspec
  - validity >=0.4 && <0.5
tests:
  genvalidity-hspec-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - genvalidity
    - genvalidity-hspec
    - hspec
  genvalidity-hspec-doctests:
    main: DocTest.hs
    source-dirs: doctests
    ghc-options: -threaded
    dependencies:
    - base
    - doctest
    - genvalidity-hspec
