name: genvalidity-hspec-hashable
version: '1.0.0.1'
synopsis: Standard spec's for Hashable instances
description: Standard spec's for Hashable instances
category: Testing
author: Nick Van den Broeck
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >=4.9 && <5
- hashable >=1.2

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - genvalidity >=1.0
  - genvalidity-hspec >=0.6
  - genvalidity-property >=0.2
  - hspec

tests:
  genvalidity-hspec-hashable-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - genvalidity
    - genvalidity-hspec
    - genvalidity-hspec-hashable
    - hashable
    - hspec
