name: genvalidity-aeson
version: '0.3.0.0'
synopsis: GenValidity support for aeson
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2017-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base
- aeson >= 1.4.0.0

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - genvalidity >=0.8
  - genvalidity-scientific >=0.2
  - genvalidity-text >=0.5
  - genvalidity-unordered-containers >=0.2
  - genvalidity-vector >=0.2
  - validity >=0.5
  - validity-aeson >=0.2

tests:
  genvalidity-aeson-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - genvalidity
    - genvalidity-hspec
    - genvalidity-aeson
    - hspec
    - deepseq

benchmarks:
  genvalidity-aeson-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - criterion
    - genvalidity-aeson
    - genvalidity-criterion
