name: genvalidity
version: '0.9.1.0'
synopsis: Testing utilities for the validity library
description: ! 'Note: There are companion instance packages for this library:


  * <https://hackage.haskell.org/package/genvalidity-aeson genvalidity-aeson>


  * <https://hackage.haskell.org/package/genvalidity-bytestring genvalidity-bytestring>


  * <https://hackage.haskell.org/package/genvalidity-containers genvalidity-containers>


  * <https://hackage.haskell.org/package/genvalidity-path genvalidity-path>


  * <https://hackage.haskell.org/package/genvalidity-scientific genvalidity-scientific>


  * <https://hackage.haskell.org/package/genvalidity-text genvalidity-text>


  * <https://hackage.haskell.org/package/genvalidity-time genvalidity-time>


  * <https://hackage.haskell.org/package/genvalidity-unordered-containers genvalidity-unordered-containers>


  * <https://hackage.haskell.org/package/genvalidity-uuid genvalidity-uuid>


  * <https://hackage.haskell.org/package/genvalidity-vector genvalidity-vector>

'
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2020 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

dependencies:
- base >=4.7 && <5

library:
  source-dirs: src
  dependencies:
  - validity >=0.9
  - QuickCheck >=2.7
  - random
  when:
  - condition: impl(ghc >=8.0.0)
    ghc-options: -Wno-redundant-constraints

tests:
  genvalidity-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hspec
    - hspec-core
    - QuickCheck
    - genvalidity
