name: genvalidity-sydtest-hashable
version: '1.0.0.1'
synopsis: Standard spec's for Hashable instances for sydtest
description: Standard spec's for Hashable instances for sydtest
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2021 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >=4.9 && <5
- hashable >=1.2

library:
  source-dirs: src
  dependencies:
  - genvalidity-sydtest
  - genvalidity >=1.0
  - sydtest
  - QuickCheck

tests:
  genvalidity-sydtest-hashable-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - genvalidity
    - genvalidity-sydtest-hashable
    - sydtest
