name: genvalidity-network-uri
version: '0.1.0.0'
synopsis: GenValidity support for URI
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2022 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity

dependencies:
- base >=4.7 && <5
- network-uri

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - genvalidity >=1.0
  - iproute
  - validity-network-uri

tests:
  genvalidity-network-uri-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - genvalidity-network-uri
    - genvalidity-sydtest
    - sydtest
    - validity-network-uri

benchmarks:
  genvalidity-network-uri-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - criterion
    - genvalidity-criterion >=1.1.0.0
    - genvalidity-network-uri
