name: genvalidity-hspec-cereal
version: '0.2.0.1'
synopsis: Standard spec's for cereal-related instances
description: Standard spec's for cereal-related Instances
category: Testing
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
homepage: http://cs-syd.eu
dependencies:
- hspec

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Test.Validity.Cereal
  dependencies:
  - base >=4.9 && <=5
  - genvalidity-hspec >=0.6
  - genvalidity >=0.5
  - cereal
  - QuickCheck
  - deepseq

tests:
  genvalidity-hspec-cereal-doctests:
    main: DocTest.hs
    source-dirs: doctest
    ghc-options: -threaded
    dependencies:
    - base
    - doctest
    - genvalidity-hspec-cereal
  genvalidity-hspec-cereal-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - genvalidity
    - genvalidity-hspec-cereal
