name: validity-dlist
version: '0.1.0.0'
synopsis: Validity instances for containers
category: Validity
author: Tom Sydney Kerckhove, Clinton Mead
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2016-2024 Tom Sydney Kerckhove, Clinton Mead'
license: MIT
github: NorfairKing/validity

extra-source-files:
- CHANGELOG.md

dependencies:
- base >=4.7 && <5
- validity >=0.5
- dlist

library:
  source-dirs: src
